config/routes.rb
Rails.application.routes.draw do
  root to: "actions#index"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "signup", to: "users#new"
  resources :users, only: [:index, :show, :create]

  resources :actions

  resources :books, only: [:new] do
    collection do
      post :search, to: "books#search"
      get :search, to: redirect("books/new")
    end
  end
end

app/models/action.rb
class Action < ApplicationRecord
  belongs_to :user

  validates :content, presence: true, length: { maximum: 500 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password

  has_many :actions
end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController
  require "net/http"

  before_action :require_user_is_login, only: [:new, :edit, :create, :update, :destroy]
  before_action :correct_user, only: [:destroy]

  def index
    @actions = Action.order(id: :desc)
  end

  def show
    @action = Action.find(params[:id])
  end

  def new
    @action = current_user.actions.build
  end

  def edit
    @action = Action.find(params[:id])
  end

  def create
    @action = current_user.actions.build(content: action_params[:content], book_title: params[:book_title], book_image: params[:book_image], book_link: params[:book_link])
    if @action.save
      flash[:success] = "アクションプランを投稿しました。"
      redirect_to root_url
    else
      flash.now[:danger] = "アクションプランの投稿に失敗しました。"
      render :new
    end
  end

  def update
    @action = Action.find(params[:id])
    if @action.update(content: action_params[:content])
      flash[:success] = "アクションプランを更新しました。"
      redirect_to @action
    else
      flash.now[:danger] = "アクションプランの更新に失敗しました。"
      render :edit
    end
  end

  def destroy
    @action = Action.find(params[:id])
    if @action.destroy
      flash[:success] = "アクションプランを削除しました。"
      redirect_to root_url
    else
      flash[:danger] = "アクションプランの削除に失敗しました。"
      render @action
    end
  end

  private

  # strong parameter
  def action_params
    params.permit(:content)
  end

  # ログインしてるユーザーの投稿かどうか判定
  def correct_user
    @action = current_user.actions.find_by(id: params[:id])
    unless @action
      redirect_to root_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  include SessionsHelper

  private

  def require_user_is_login
    unless is_login
      redirect_to login_url
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :require_user_is_login, only: [:new, :search]

  def new
  end

  def search
    @books = get_json_from_url(url_from_keyword(params[:keyword]))
    render :new
  end

  private

  # URLからJSONデータを取得
  def get_json_from_url(url)
    JSON.parse(Net::HTTP.get(URI.parse(URI.encode(url))))
  end

  # キーワードからURLを作成
  def url_from_keyword(keyword)
    "https://www.googleapis.com/books/v1/volumes?q=#{keyword}&country=JP&maxResults=20"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(id: :desc)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "ユーザーを登録しました"
      redirect_to login_url
    else
      flash.now[:danger] = "ユーザーの登録に失敗しました"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def is_login
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/actions/edit.html.erb
<div class="content-header">
  <h2>アクションプラン id:<%= @action.id %> 編集</h2>
</div>

<div class="action-show">
  <div class="action-show-info">
    <div class="book-item">
      <%= image_tag @action.book_image || "no-image.jpg", alt: @action.book_title, class: "book-image" %>
      <p class="book-title"><%= @action.book_title %></p>
      <%= link_to "show detail", @action.book_link, class: "book-link btn btn-light btn-block mb-1", target: "_blank" %>
    </div>
    <p class="action-show-user">投稿者<br><%= User.find(@action.user_id).name %></p>
  </div>
  <div class="action-plan-text-area">
    <%= form_with url: action_url, local: true, method: "patch" do |f| %>
      <%= f.text_area :content, value: @action.content, class: "form-control", rows: 15 %>
      <div class="action-plan-button-area">
        <%= f.submit "変更を保存", class: "action-plan-button btn btn-light" %>
      </div>
    <% end %>
  </div>
</div>

app/views/actions/index.html.erb
<div class="content-header">
  <h2>アクションプラン<br class="sp-only">投稿一覧</h2>
  <a class="btn btn-dark" href="<%= new_book_path %>">アクションプラン<br class="sp-only">新規投稿</a>
</div>

<% if @actions %>
  <div class="action-list">
    <% @actions.each do |action| %>
      <a class="action-item" href="<%= action_path(action) %>">
        <div class="book-item">
          <%= image_tag action.book_image || "no-image.jpg", alt: action.book_title, class: "book-image" %>
          <p class="book-title"><%= action.book_title %></p>
        </div>
        <p class="action-content"><%= action.content %></p>
      </a>
    <% end %>
  </div>
<% end %>

app/views/actions/new.html.erb
<div class="content-header">
  <h2>アクションプラン新規投稿</h2>
</div>

<div class="post-stage-box">
  <div class="post-stage">書籍選択</div>
  <div class="post-stage current-stage">アクションプラン</div>
</div>

<div class="post-action-plan">
  <p>255文字まで入力できます</p>
  <%= form_with url: actions_url, local: true do |f| %>
    <%= hidden_field_tag :book_title, params[:book_title] %>
    <%= hidden_field_tag :book_image, params[:book_image] %>
    <%= hidden_field_tag :book_link, params[:book_link] %>
    <%= f.text_area :content, class: "form-control mb-2", rows: 5 %>
    <%= f.submit "Post", class: "btn btn-primary btn-block" %>
  <% end %>
</div>

app/views/actions/show.html.erb
<div class="content-header">
  <h2>アクションプラン id:<%= @action.id %></h2>
</div>

<div class="action-show">
  <div class="action-show-info">
    <div class="book-item">
      <%= image_tag @action.book_image || "no-image.jpg", alt: @action.book_title, class: "book-image" %>
      <p class="book-title"><%= @action.book_title %></p>
      <%= link_to "show detail", @action.book_link, class: "book-link btn btn-light btn-block mb-1", target: "_blank" %>
    </div>
    <p class="action-show-user">投稿者<br><%= User.find(@action.user_id).name %></p>
  </div>
  <div class="action-plan-text-area">
    <p class="action-plan-text"><%= safe_join((@action.content ||= "").split("\n"),tag(:br)) %></p>
    <% if is_login && current_user.id == @action.user_id %>
      <div class="action-plan-button-area">
        <%= link_to "削除", action_url, method: "delete", class: "action-plan-button btn btn-light" %>
        <%= link_to "編集", edit_action_url, class: "action-plan-button btn btn-light" %>
      </div>
    <% end %>
  </div>
</div>

app/views/books/new.html.erb
<div class="content-header">
  <h2>アクションプラン新規投稿</h2>
</div>

<div class="post-stage-box">
  <div class="post-stage current-stage">書籍選択</div>
  <div class="post-stage">アクションプラン</div>
</div>

<%= form_with url: search_books_path, class: "row mb-1", local: true do |f| %>
  <%= f.text_field :keyword, class: "form-control col-10", placeholder: "書籍名、著者名で検索" %>
  <%= f.submit "検索", class: "btn btn-light col-2" %>
<% end %>

<% if books_items = (@books ||= {}).dig("items") %>
  <ul class="book-list">
    <% books_items.each do |book| %>
      <% if book_info = book.dig("volumeInfo") %>
        <li class="book-item">
          <%= image_tag book_image = book_info.dig("imageLinks", "thumbnail") || "no-image.jpg", alt: book_title = book_info.dig("title"), class: "book-image" %>
          <p class="book-title"><%= book_title %></p>
          <%= link_to "show detail", book_link = book_info.dig("infoLink"), class: "book-link btn btn-light btn-block mb-1", target: "_blank" %>
          <%= form_with url: new_action_path, method: "get", local: true do |f| %>
            <%= hidden_field_tag :book_title, book_title %>
            <%= hidden_field_tag :book_image, book_image %>
            <%= hidden_field_tag :book_link, book_link %>
            <%= f.submit "select book", class: "btn btn-light btn-block" %>
          <% end %>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-fluid navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Action Plan</a>
    <ul class="navbar-nav flex-row">
      <% if is_login %>
        <li class="nav-item"><%= link_to "Users", users_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Logout", logout_path, class: "nav-link ml-3", method: :delete %></li>
      <% else %>
        <li class="nav-item"><%= link_to "Users", users_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Signup", signup_path, class: "nav-link ml-3" %></li>
        <li class="nav-item"><%= link_to "Login", login_path, class: "nav-link ml-3" %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Action Plan</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <main>
      <%= render "layouts/flash_message" %>
      <%= yield %>
    </main>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <!-- popper js -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <!-- Bootstrap js -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/index.html.erb
<div class="content-header">
  <h2>ユーザー一覧</h2>
</div>

<% if @users %>
  <div class="user-list">
    <% @users.each do |user| %>
      <a class="user-item" href="<%= user_path(user) %>">
        <p class="user-name"><%= user.name %></p>
        <p class="user-action-number">アクションプラン投稿数：<%= user.actions.count %></p>
      </a>
    <% end %>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= form_with(model: @user, local: true) do |f| %>

      <div class="form-group">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :email, "Email" %>
        <%= f.email_field :email, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :password, "Password" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>

      <%= f.submit "Sign up", class: "btn btn-primary btn-block" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="content-header">
  <h2><%= @user.name %>さんのユーザーページ<br><%= @user.name %>さんの投稿一覧</h2>
</div>

<% if @user.actions %>
  <div class="action-list">
    <% @user.actions.each do |action| %>
      <a class="action-item" href="<%= action_path(action) %>">
        <div class="book-item">
          <%= image_tag action.book_image || "no-image.jpg", alt: action.book_title, class: "book-image" %>
          <p class="book-title"><%= action.book_title %></p>
        </div>
        <p class="action-content"><%= action.content %></p>
      </a>
    <% end %>
  </div>
<% end %>